# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [workflow_dispatch]
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: Ubuntu-Latest
    #[self-hosted, Linux]
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package
        #run: ./mvnw spring-boot:build-image
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mybuildartifact
          path: '${{ github.workspace }}/target/*.jar'
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: mybuildartifact
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: |
          docker build --help
          docker build -t < .devcontainer/Dockerfile
